export default [
  "AGON",
  "ALIEN",
  "Apocalypse World",
  "Blades in the Dark",
  "Brindlewood Bay",
  "Call of Cthulhu",
  "Carved from Brindlewood",
  "Cyberpunk",
  "Deathmatch Island",
  "Delta Green",
  "Descended from the Queen",
  "Dungeons & Dragons 5th Edition",
  "Dungeon World",
  "Fate",
  "Fiasco",
  "Forged in the Dark",
  "Heart",
  "Ironsworn",
  "Lasers & Feelings",
  "Masks",
  "Monsterhearts",
  "Monster of the Week",
  "Mörk Borg",
  "Mothership",
  "Night Witches",
  "Numenera",
  "Old-School Essentials",
  "Paragon System",
  "Pathfinder 2nd Edition",
  "Powered by the Apocalypse",
  "Public Access",
  "Rooted in Trophy",
  "Savage Worlds",
  "Shadowrun",
  "Spire",
  "Starfinder",
  "Starforged",
  "Star Trek",
  "Star Wars",
  "The Between",
  "The One Ring",
  "The Silt Verses",
  "Thirsty Sword Lesbians",
  "Troika",
  "Trophy Dark",
  "Trophy Gold",
  "Stars Without Number",
  "Vampire: The Masquerade",
  "Wanderhome",
  "Warhammer",
];

export const GAME_TAGS = [
  "Call of Cthulhu",
  "card-based",
  "CfB",
  "Crunchy",
  "Cyberpunk",
  "D&D",
  "DftQ",
  "Fantasy",
  "Fate",
  "FitD",
  "gmless",
  "Indie",
  "LARP",
  "Narrative",
  "OSR",
  "PbtA",
  "RiT",
  "Rules light",
  "Sci-fi",
  "Star Trek",
  "Star Wars",
  "Story games",
  "VTT",
];

export const GAME_TAG_OPTIONS = GAME_TAGS.map((val) => ({
  label: val,
  value: val,
}));
