export default [
  "ALIEN",
  "Apocalypse World",
  "Blades in the Dark",
  "Call of Cthulhu",
  "Cyberpunk",
  "Delta Green",
  "Dungeons & Dragons 5th Edition",
  "Dungeon World",
  "Fate",
  "Fiasco",
  "Heart",
  "Ironsworn",
  "Masks",
  "Monsterhearts",
  "Monster of the Week",
  "Mörk Borg",
  "Mothership",
  "Night Witches",
  "Old-School Essentials",
  "The One Ring",
  "Pathfinder 2nd Edition",
  "Savage Worlds",
  "Shadowrun",
  "Starfinder",
  "Starforged",
  "Star Trek",
  "Star Wars",
  "Thirsty Sword Lesbians",
  "Troika",
  "Trophy Dark",
  "Trophy Gold",
  "Stars Without Number",
  "Vampire: The Masquerade",
  "Wanderhome",
  "Warhammer",
];
